CREATE TABLE IF NOT EXISTS courses(
    course_code TEXT PRIMARY KEY,
    lev TEXT,
    title TEXT,
    department TEXT,
    credit_units INTEGER,
    outline TEXT
);

INSERT INTO courses(course_code, lev, title, department, credit_units, outline) VALUES
('DCS101', 'Diploma 1', 'Introduction to Computer technology', 'Computer Science', 2, 'History of technology, First Computers, Types of Computers.'),
('DCS102', 'Diploma 1', 'Discrete Mathematics',	'Computer Science',	3,	'Study of mathematical structures in computer science.'),
('DCS103', 'Diploma 1', 'Digital Logic Design',	'Computer Science',	4,	'Introduction to digital circuits and logic design.'),
('DCS104', 'Diploma 1', 'Data Structures',	'Computer Science',	4,	'Introduction to data structures and algorithms.'),
('DCS105', 'Diploma 1', 'Computer Organization', 'Computer Science', 3,	'Understanding computer architecture and organization.'),
('DCS106', 'Diploma 1', 'Object-Oriented Programming',	'Computer Science',	4,	'Advanced programming using object-oriented concepts.'),
('DCS107', 'Diploma 1', 'Operating Systems',	'Computer Science',	3,	'Principles of operating systems and processes.'),
('DCS108', 'Diploma 1', 'Database Systems',	'Computer Science',	4,	'Introduction to database design and SQL.'),
('DCS109', 'Diploma 1', 'Computer Networks',	'Computer Science',	3,	'Basics of networking and data communication.'),
('DCS110', 'Diploma 1', 'Software Engineering',	'Computer Science',	4,	'Fundamentals of software development and management.'),
('DCS202', 'Diploma 2', 'Theory of Computation',	'Computer Science',	4,	'Study of automata, computability, and complexity.'),
('DCS203', 'Diploma 2',	'Compiler Design',	'Computer Science',	4,	'Introduction to the design and implementation of compilers.'),
('DCS204', 'Diploma 2',	'Artificial Intelligence',	'Computer Science',	3,	'Basics of AI, including machine learning and robotics.'),
('DCS205', 'Diploma 2',	'Machine Learning',	'Computer Science',	4,	'Introduction to machine learning algorithms and applications.'),
('DCS206', 'Diploma 2',	'Computer Graphics',	'Computer Science',	4,	'Fundamentals of computer graphics and visualization.'),
('DCS207', 'Diploma 2',	'Web Development',	'Computer Science',	3,	'Study of web technologies and development practices.'),
('DCS208', 'Diploma 2',	'Mobile Application Development',	'Computer Science',	4,	'Design and development of mobile applications.'),
('DCS209', 'Diploma 2',	'Cyber Security',	'Computer Science',	3,	'Principles of cybersecurity and information protection.'),
('DCS210', 'Diploma 2',	'Distributed Systems',	'Computer Science',	4,	'Introduction to distributed computing systems.'),
('DCE101', 'Diploma 1', 'Circuit Theory',	'Computer Engineering',	3,	'Fundamentals of electrical circuits and systems.'),
('DCE103', 'Diploma 1', 'Signals and Systems',	'Computer Engineering',	4,	'Study of signals, systems, and signal processing.'),
('DCE104', 'Diploma 1', 'Electromagnetics',	'Computer Engineering',	4,	'Introduction to electromagnetic fields and waves.'),
('DCE105', 'Diploma 1', 'Microprocessors',	'Computer Engineering',	4,	'Basics of microprocessor architecture and programming.'),
('DCE106', 'Diploma 1', 'Digital Electronics',	'Computer Engineering',	4,	'Advanced study of digital circuits and systems.'),
('DCE107', 'Diploma 1', 'Communication Systems',	'Computer Engineering',	3,	'Principles of communication systems and networks.'),
('DCE108', 'Diploma 1', 'Control Systems',	'Computer Engineering',	4,	'Study of control systems and automation.'),
('DCE109', 'Diploma 1', 'Power Electronics',	'Computer Engineering',	3,	'Introduction to power electronics and converters.'),
('DCE110', 'Diploma 1', 'Embedded Systems',	'Computer Engineering',	4,	'Fundamentals of embedded systems design.'),
('DCE201', 'Diploma 2',	'Advanced Circuit Theory',	'Computer Engineering',	4,	'Advanced study of electrical circuit analysis and design.'),
('DCE202', 'Diploma 2',	'Electronics II',	'Computer Engineering',	4,	'Continuation of electronics with complex circuits.'),
('DCE203', 'Diploma 2',	'Digital Signal Processing',	'Computer Engineering',	4,	'Introduction to digital signal processing techniques.'),
('DCE204', 'Diploma 2',	'Antennas and Wave Propagation','Computer Engineering',	4,	'Study of antennas and electromagnetic wave propagation.'),
('DCE205', 'Diploma 2',	'VLSI Design',	'Computer Engineering',	4,	'Basics of VLSI technology and circuit design.'),
('DCE206', 'Diploma 2',	'Robotics and Automation',	'Computer Engineering',	4,	'Principles of robotics, automation, and control.'),
('DCE207', 'Diploma 2',	'Analog and Digital Communication',	'Computer Engineering',	4,	'Study of analog and digital communication techniques.'),
('DCE208', 'Diploma 2',	'Power Systems',	'Computer Engineering',	3,	'Introduction to power generation, transmission, and distribution.'),
('DCE209', 'Diploma 2',	'Advanced Embedded Systems',	'Computer Engineering',	4,	'In-depth study of embedded systems design and applications.'),
('DCE210', 'Diploma 2',	'Renewable Energy Systems',	'Computer Engineering',	3,	'Fundamentals of renewable energy technologies and systems.');